# antora generate --clean --to-dir public playbook.yml
# antora generate playbook.yml
# ln -s ../../../../../README.adoc index.adoc
site:
  title: 安宁的知识库
  url: https://peacetrue.github.io
  start_page: overview::index.adoc
asciidoc:
  extensions:
    - asciidoctor-plantuml
  attributes:
    plantuml-server-url: 'http://www.plantuml.com/plantuml@'
    numbered: '@'
    website: https://peacetrue.github.io
    root-dir: docs/antora/modules/ROOT
    root-dir-reverse: ../../../..
    examples-dir: docs/antora/modules/ROOT/examples
    examples-dir-reverse: ../../../../..
content:
  branches: master
  sources:
  - url: ./
    start_path: docs/antora
  - url: https://github.com/peacetrue/peacetrue-shell.git
    start_path: docs/antora
  - url: https://github.com/peacetrue/peacetrue-beans.git
    start_path: docs/antora
  - url: https://github.com/peacetrue/peacetrue-common.git
    start_path: docs/antora
  - url: https://github.com/peacetrue/peacetrue-cryptography.git
    start_path: docs/antora
  - url: https://github.com/peacetrue/peacetrue-result.git
    start_path: docs/antora
#  - url: https://github.com/peacetrue/peacetrue-tplngn.git
#    start_path: docs/antora
#  - url: https://github.com/peacetrue/peacetrue-template.git
#    start_path: docs/antora
  - url: https://github.com/peacetrue/peacetrue-test.git
    start_path: docs/antora
  - url: https://github.com/peacetrue/bee.git
    start_path: docs/antora
#  - url: https://github.com/peacetrue/peacetrue-core
#    start_path: docs/antora
#  - url: https://github.com/peacetrue/learn-antora
#    start_path: docs/antora
#  - url: https://github.com/peacetrue/learn-spring-framework
#    branches: master
#    start_path: docs/antora
#  - url: https://github.com/peacetrue/peacetrue-template-model-library
#    branches: snapshot/2.0
#    start_path: docs/antora

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: supplemental-ui
#output:
#  clean: true
#  dir: ./site
#  destinations:
#    - provider: archive
