@startuml
'top to bottom direction
left to right direction

cloud {
  [应用1.1]
  [应用1.2]
}

database "版本控制仓库" {
    folder "应用外壳"{
        folder "WebMVC" {
            [版本10.1]
            [版本10.2]
        }
        folder "WebFlux" {
            [版本11.1]
            [版本11.2]
        }
    }
    folder "应用内核"{
        folder "用户模块" {
            [版本1.1]
            [版本1.2]
        }
        folder "其他模块" {
            [版本2.1]
            [版本2.2]
        }
    }
}


[应用1.1] --> [版本1.1]
[应用1.1] --> [版本2.1]
[应用1.1] --> [版本10.1]

[应用1.2] --> [版本1.2]
[应用1.2] --> [版本2.2]
[应用1.2] --> [版本11.2]

@enduml
