= 人生伴侣

//@formatter:off

每个人心中都会有一个理想的伴侣的吧。
也许不是非常明确，但或多或少会有一个大概的轮廓。
理想也许可以企及，但不知要到何时；
巧合也是缘分，我觉得你还挺好的，也感谢长辈的支持吧。

不知道你会喜欢什么样的，大概介绍一下自己，供你参考吧。

中规中矩的一个人，没有什么不良嗜好。
家住中州七队，离你家还挺近的吧，20 里路；
三口之家独生子，家庭和睦安康。

一直从事软件开发，挺喜欢的，以后也会一直做下去。
大部分时间应该会花在：你、读书和电脑上。

长时间坐久了，还是要运动一下，每周都会打打羽毛球；
滑冰也挺喜欢的。如果你也喜欢就太好了，
当然如果你有自己喜欢的运动，也可以尝试一起。
休息的时候，会上 B 站看看动漫。

理想中的生活大概是这样吧。
双方家庭都能买一些医疗保险，以免意外事故或疾病造成个人难以抗拒的风险。
遇到事情，两个人能相互商量，得出结论；
不能接受，遇到问题，逃避解决，没有回应；可以是肯定或者否定的答复，但不能没有回应。
不触犯原则性问题，相互之间，求同存异，包容接纳。
有时间，可以一起做做饭，谈谈喜欢的事物，工作上相互支持。

长时间异地不能接受，如果你现在工作比较稳定，我去深圳也可行。

不能说，能够提高彼此的生活质量吧；但肯定不会降低你的生活的质量。

你有什么想法，也可以一起探讨。


我也大概说下吧，我一直都从事品牌策划，还比较喜欢，如果不出意外，会做下去吧，家在老街大堤下面，四口之家，有一个弟弟，小6岁，家庭比较和睦，老妈身体不是很好。

我从小一直都在外面，小时候在奶奶家，初中在姑姑家，记忆里很少回家，出去上大学工作以后就更少回家了，目前每年会回去一两趟这样。

平时爱好比较广泛，羽毛球也打，看书画画尤克里里（貌似好久没弹了），桌球，旅游，爬山，滑冰还不会，但是也不排斥，能接受新鲜事物，还有很累的时候喜欢躺平

理想生活，我喜欢被爱和呵护，喜欢对我大方，舍得付出的，拒绝冷暴力，有矛盾的时候，我气头上的时候可能不想讲话，不过我忘性大，一会就好了，好了以后可以沟通。

有时间可以一起做做饭，也可以各自做自己喜欢的事情。

异地的问题要考虑以后的发展问题，我不一定非要在深圳，但是如果是武汉，一切从头开始我可能缺乏安全感，需要好好考虑

我平时工作比较忙，不去酒吧，除非公司/部门团建等特殊时候，基本大的开支来源就是平时的护肤品会比较贵，喜欢买一些大品牌的奢侈品。

基本是这样
