= 面试

== 招聘公司
* 猎聘
* 拉钩
* boss直聘
* 前程无忧
* 51job
* 智联
* 领英

作为招聘方，我们也一直觉得各种平台推过来的人经常不对口。 +
平台只能做一些基础岗位，根本不愿意花时间来了解我们用人单位的需求。 +
随便给几份简历，就开始推销套餐要收费了


常见要求

== jvm

https://www.cnblogs.com/rinack/p/9888692.html

* Eden：伊甸园
* From Survivor：来自幸存者
* To Survivor：至幸存者
* 1v1

== 简单心理
=== 中高级 Web 前端开发工程师
==== 工作职责
【公司产品前端平台和组件】的设计与方案讨论::
这个主要考逻辑能力，有了java的面向对象背景，设计能力上还是不错的
开发并且维护【公司产品前端平台和组件】::
个人非常喜欢开发组件，之前基于 jQuery 和 jQuery-ui 就开发过不少组件，
后来到了 node 时代，也开发基于 vue 的组件，比如说：基于 iview 的上传组件、基于 async-validate 的扩展组件、基于 axios 的扩展组件等等。
编写高质量、结构清晰、易读、易维护的代码::
表示对代码有洁癖，喜欢干净简洁易读的代码，代码就是最好的文档
建立并且持续维护开发文档::
之前不太喜欢写文档，但现在越来越喜欢写文档了，喜欢总结和提炼一些通用的思想和逻辑，沉淀下来。
使用 adoc 编写文档，并使用 antora 进行跨资源库的统一管理

==== 任职要求
熟练掌握 HTML/CSS，原生 JavaScript 能力，熟悉 Linux 部署环境::
这么多年过来一路见证了 HTML/CSS/JavaScript 的不断升级和发展，
以及各种 JavaScript 框架的更新迭代，风起云涌，瞬息万变。
经常用 Linux 系统，之前部署过 nginx 和 tomcat，现在换 docker 就没弄过了。
熟练掌握常用的前端编程范式，如事件驱动、数据驱动等::
事件驱动、数据驱动 好理解，倒是对前端编程范式不太清楚，还有哪些前端范式呢？
函数式编程&防御式编程&响应式编程&契约式编程&流式编程，算么。
熟悉 Restful API、JSON API、JWT 等常用接口实践::
作为后台开发，这些在项目中都实际用过。
Spring HATEOAS 可用于支持 JSON API。
JWT 用在按时长一次性授权四处可用的场景。
熟练掌握 React/Vue 等主流前端框架，熟练使用 Node.JS::
React 自己学过，没在项目中用过；项目中用的是 Vue \+ iview，
用 Vue \+ webpack 写过类库， Node.JS 连过数据库。
熟练使用 Gulp、Webpack 等自动构建工具，熟练使用 Git 开发和管理代码::
Gulp 没用过，只用过 Webpack。后台开发 Git 使用太频繁了。
了解基本的数据库概念和使用方法，包括SQL、Redis等::
SQL、Redis 是作为后台开发的基础知识了
有良好的编程习惯，沟通能力强，能够独自编写技术文档::
看一个我写的接口文档规范吧， https://peacetrue.github.io/public/overview/standard/api/index.html
具备较强的学习能力、问题分析能力，具备独立解决问题的能力::
开发呢，必备 Google 吧，有 Google 相助，解决问题效率提升 50%， 一般都看官方文档，虽然英语不怎么好，但多半都能看懂。
良好的沟通协调能力和团队合作意识，工作踏实，态度积极，能够承受工作压力::
基本职业素养，人人必备。
熟悉 React Native/Weex/Flutter 等跨平台 App 框架::
不熟悉，没用过，立马学一下
有大型前端项目工作经验::
大型，什么算大型，之前做的应该不算大型吧

